# === Identificación del proyecto ===
sonar.projectKey=gestion_contractual_compras_root_mf
sonar.projectName=gestion_contractual_compras_root_mf
sonar.projectVersion=1.0

# === Directorios del código fuente ===
sonar.sources=src

# === Exclusiones (archivos o carpetas que no se analizan) ===
sonar.exclusions=**/node_modules/**,**/*.spec.*,**/*.test.*,**/dist/**

# === Configuración de pruebas ===
sonar.tests=src
sonar.test.inclusions=**/*.spec.*,**/*.test.*

# === Lenguaje y codificación ===
sonar.sourceEncoding=UTF-8
